(define (averager a b c)
  (let ((d (make-connector)) (e (make-connector)))
    (adder a b d)
    (multiplier c e d)
    (constant 2 e)
    'ok))

(define a (make-connector))
(define b (make-connector))
(define c (make-connector))
(averager a b c)
(probe "average" c)
(probe "data-1" a)
(probe "data-2" b)

(set-value! a 18 'user)
(set-value! b 12 'user)
(forget-value! b 'user)
(set-value! b 25 'user)
