(define (make-account balance password)
  (define (withdraw amount)
    (if (<= amount balance)
      (begin (set! balance (- balance amount)) balance)
      "Insufficient"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount)) balance))
  (define (incorrect-password m) "Incorrect password")
  (define (dispatch m input)
    (if (eq? password input)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request" m)))
      incorrect-password))
  dispatch)

(define acc (make-account 100 'secret-password))

((acc 'deposit 'secret-password) 50)
